analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.2228786
  brandColors:
    - '#20201F'
    - '#FFFCFF'
    - '#CFC6B4'
    - '#B4785C'
    - '#4A30BC'
  rhythmicContrast: 0.66971
typography_spectrum: 0.2529538
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: My Dirt Church
