typography_spectrum: 0.42119
color:
  saturation: 0.83942
  brandStrength: 0.03920516
  lightness: 0.6589689
  brandColors:
    - '#E9B56D'
    - '#BEB3BD'
    - '#02010C'
    - '#397FBD'
    - '#041665'
  rhythmicContrast: 0.6525242
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9758323
analytics:
  twitter: null
  google: null
  facebook: null
name: '#mydirtchurch'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Trip Reports
    id: fd4e5e97-6b64-4d21-a524-1bfc0f652729
    type: content
  - name: Gear List
    url: 'https://thegrid.ai/my-dirt-church/gear-list/'
    type: external
  - name: Social
    url: 'https://thegrid.ai/my-dirt-church/social/'
    type: external
  - name: Contact
    url: 'https://thegrid.ai/my-dirt-church/contact/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Dirt Church
description: outdoor zen
purpose: []
