layout_spectrum: 0.5
color:
  saturation: 0.8041895
  lightness: 0.7952461
  brandStrength: 0.7199796
  rhythmicContrast: 0.3818018
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.5899536
name: My Dirt Church
