name: My Dirt Church
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41299
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F1DFE1'
    - '#1E170D'
    - '#9AA4B4'
    - '#CF885C'
    - '#A3201F'
  brandStrength: 0.9962406
  lightness: 0.75
  saturation: 0.9844254
  rhythmicContrast: 1
purpose: []
